#include "LIVMapper.h"
#include <algorithm>
#include <csignal>
#include <iomanip>
#include <iostream>
#ifdef _WIN32
#include <fcntl.h>
#include <io.h>
#endif

namespace {
volatile std::sig_atomic_t cancelled=0;
void stop(int){cancelled=1;}
template<class T> T read(std::istream& in){T v{};if(!in.read(reinterpret_cast<char*>(&v),sizeof(v)))throw std::runtime_error("Truncated input record");return v;}
void help(){std::cout << "FAST-LIVO2 native offline 0.1.0\n"
 "Usage: fastlivo2 --input capture.flv2 --config raven.yaml --camera camera_raven.yaml --output DIR [--lio] [--threads N]\n"
 "Use --input - for binary stdin. FLV2 input is generated by RavenCalibrator export-bag.\n"
 "No ROS or WSL required. Output: DIR/pcd/all_raw_points.pcd and DIR/result/*.txt.\n";}
}
int main(int argc,char** argv){
 try {
  std::string input,config,camera,output;bool lio=false;int threads=4;
  for(int i=1;i<argc;++i){std::string a=argv[i];
   if(a=="--help"||a=="-h"){help();return 0;}
   if(a=="--version"){std::cout<<"fastlivo2 native 0.1.0\n";return 0;}
   if(a=="--lio"){lio=true;continue;}
   if(i+1>=argc)throw std::runtime_error("Missing value for "+a);
   std::string v=argv[++i];
   if(a=="--input")input=v;else if(a=="--config")config=v;else if(a=="--camera")camera=v;
   else if(a=="--output")output=v;else if(a=="--threads")threads=std::stoi(v);
   else throw std::runtime_error("Unknown option: "+a);
  }
  if(input.empty()||config.empty()||camera.empty()||output.empty()){help();return 2;}
  if(threads<1||threads>256)throw std::runtime_error("Threads must be 1..256");
  native::config=YAML::LoadFile(config);native::camera=YAML::LoadFile(camera);
  if(lio)native::config["common"]["img_en"]=0;
  native::config["uav"]["imu_rate_odom"]=false;
  native::config["publish"]["pub_plane_en"]=false;
  native::config["pcd_save"]["colmap_output_en"]=false;
  native::config["pcd_save"]["pcd_save_en"]=true;
  native::config["pcd_save"]["interval"]=-1;
  native::config["evo"]["pose_output_en"]=true;
  for(const auto& key:{"extrinsic_T","extrinsic_R","Pcl","Rcl"}){
   size_t expected=(std::string(key)=="extrinsic_T"||std::string(key)=="Pcl")?3:9;
   if(native::config["extrin_calib"][key].size()!=expected)throw std::runtime_error(std::string("Invalid extrinsic array: ")+key);
  }
  const auto seq=native::config["evo"]["seq_name"].as<std::string>("01");
  if(seq.empty()||seq.find_first_of("/\\:")!=std::string::npos||seq=="..")throw std::runtime_error("Invalid trajectory name");
  const auto out=std::filesystem::absolute(output);
  if(std::filesystem::exists(out/"pcd/all_raw_points.pcd")||std::filesystem::exists(out/"result"/(seq+".txt")))
   throw std::runtime_error("Output already contains SLAM results; choose a new output directory");
  native::output_root=out.generic_string()+"/";
  native::threads=threads;omp_set_num_threads(threads);cv::setNumThreads(threads);
  std::ifstream file;std::istream* stream=&std::cin;
  if(input!="-"){file.open(input,std::ios::binary);if(!file)throw std::runtime_error("Cannot open input");stream=&file;}
  else {
#ifdef _WIN32
   _setmode(_fileno(stdin),_O_BINARY);
#endif
  }
  char magic[8];if(!stream->read(magic,8)||std::string(magic,8)!=std::string("FLV2\x01\0\0\0",8))throw std::runtime_error("Invalid FLV2 input header");
  ros::NodeHandle nh;LIVMapper mapper(nh);
  if(mapper.p_pre->feature_enabled)throw std::runtime_error("Offline input supports feature_extract_enabled=false only");
  if(mapper.p_pre->point_filter_num<1||mapper.filter_size_surf_min<=0)throw std::runtime_error("Invalid preprocessing configuration");
  std::signal(SIGINT,stop);std::signal(SIGTERM,stop);
#ifdef _WIN32
  std::signal(SIGBREAK,stop);
#endif
  std::array<double,4> last{-1,-1,-1,-1};size_t records=0,scans=0,updates=0;
  const auto started=std::chrono::steady_clock::now();
  while(!cancelled && stream->peek()!=EOF){
   auto kind=read<uint8_t>(*stream);auto timestamp=read<double>(*stream);auto count=read<uint32_t>(*stream);
   if(kind<1||kind>3||!std::isfinite(timestamp)||timestamp<last[kind])throw std::runtime_error("Invalid or non-monotonic sensor timestamp");
   last[kind]=timestamp;
   if(kind==1){
    if(count!=6)throw std::runtime_error("Invalid IMU record length");
    auto m=std::make_shared<sensor_msgs::Imu>();m->header.stamp.fromSec(timestamp);
    m->angular_velocity={read<double>(*stream),read<double>(*stream),read<double>(*stream)};
    m->linear_acceleration={read<double>(*stream),read<double>(*stream),read<double>(*stream)};
    if(!std::isfinite(m->angular_velocity.x+m->angular_velocity.y+m->angular_velocity.z+m->linear_acceleration.x+m->linear_acceleration.y+m->linear_acceleration.z))throw std::runtime_error("Non-finite IMU sample");
    mapper.imu_cbk(m);
   }else if(kind==2){
    if(count>10000000)throw std::runtime_error("Scan exceeds 10 million points");
    std::vector<std::array<float,5>> packed(count);
    if(!stream->read(reinterpret_cast<char*>(packed.data()),static_cast<std::streamsize>(count)*20))throw std::runtime_error("Truncated scan");
    PointCloudXYZI::Ptr cloud(new PointCloudXYZI);cloud->reserve(count);
    for(uint32_t i=0;i<count;++i){PointType p{};p.x=packed[i][0];p.y=packed[i][1];p.z=packed[i][2];p.intensity=packed[i][3];p.curvature=packed[i][4];
     if(!std::isfinite(p.x+p.y+p.z+p.intensity+p.curvature))continue;
     if(p.curvature<0||p.curvature>1000)throw std::runtime_error("Point offset outside 0..1000 milliseconds");
     if(i%mapper.p_pre->point_filter_num==0 && p.x*p.x+p.y*p.y+p.z*p.z>mapper.p_pre->blind_sqr)cloud->push_back(p);
    }
    if(cloud->size()>1){std::sort(cloud->begin(),cloud->end(),[](const PointType&a,const PointType&b){return a.curvature<b.curvature;});
     mapper.lid_raw_data_buffer.push_back(cloud);mapper.lid_header_time_buffer.push_back(timestamp+mapper.lidar_time_offset);mapper.last_timestamp_lidar=timestamp+mapper.lidar_time_offset;++scans;}
   }else{
    if(count>128*1024*1024)throw std::runtime_error("Image exceeds 128 MiB");
    std::vector<unsigned char> bytes(count);if(!stream->read(reinterpret_cast<char*>(bytes.data()),count))throw std::runtime_error("Truncated image");
    if(mapper.img_en){auto m=std::make_shared<sensor_msgs::Image>();m->header.stamp.fromSec(timestamp);m->image=cv::imdecode(bytes,cv::IMREAD_COLOR);if(m->image.empty())throw std::runtime_error("Cannot decode image");mapper.img_cbk(m);}
   }
   ++records;
   // Call again when sync discards an old image, but stop when it needs input.
   for(;;){auto before=mapper.img_buffer.size();if(!mapper.sync_packages(mapper.LidarMeasures)){if(mapper.img_buffer.size()<before)continue;break;}
    mapper.handleFirstFrame();mapper.processImu();mapper.stateEstimationAndMapping();++updates;
   }
   if(mapper.lid_raw_data_buffer.size()>1000||mapper.img_buffer.size()>100||mapper.imu_buffer.size()>200000)
    throw std::runtime_error("Sensor queues exceeded limits: check topics and time offsets");
  }
  if(stream->bad())throw std::runtime_error("Input I/O failure");
  mapper.savePCD();
  if(!mapper.lid_raw_data_buffer.empty())std::cerr<<"Warning: "<<mapper.lid_raw_data_buffer.size()<<" trailing scans are outside synchronized sensor coverage and were not mapped.\n";
  const double elapsed=std::chrono::duration<double>(std::chrono::steady_clock::now()-started).count();
  const auto points=mapper.img_en?mapper.pcl_wait_save->size():mapper.pcl_wait_save_intensity->size();
  std::ofstream report(out/"run.json");
  report<<"{\"records\":"<<records<<",\"scans\":"<<scans<<",\"updates\":"<<updates<<",\"points\":"<<points<<",\"elapsed_seconds\":"<<elapsed<<",\"cancelled\":"<<(cancelled?"true":"false")<<",\"pending_scans\":"<<mapper.lid_raw_data_buffer.size()<<"}\n";
  if(cancelled)return 130;
  if(!points)throw std::runtime_error("No map produced: insufficient initialization or unsynchronized sensors");
  std::cout<<"Completed: "<<points<<" points in "<<elapsed<<" seconds\n";return 0;
 }catch(const std::exception& e){std::cerr<<"fastlivo2: "<<e.what()<<"\n";return 2;}
}
